version: '3'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install mlflow &&
              mlflow server \
              --host 0.0.0.0 \
              --port 5000"
    volumes:
      - ./mlruns:/mlruns